version: "3.5"

services:
  golangci-lint:
    image: golangci/golangci-lint:v2.0.2
    working_dir: /app
    volumes:
      - ..:/app:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache
    environment:
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
  goreleaser:
    image: goreleaser/goreleaser-pro:v2.8.2
    environment:
      - BUILDKITE_AGENT_JOB_API_SOCKET
      - BUILDKITE_AGENT_JOB_API_TOKEN
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
    working_dir: /go/src/github.com/buildkite/buildkite-mcp-server
    volumes:
      - ..:/go/src/github.com/buildkite/buildkite-mcp-server:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache      
      - ${BUILDKITE_AGENT_JOB_API_SOCKET}:${BUILDKITE_AGENT_JOB_API_SOCKET}